repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      # Ensures that (non-binary) executables have a shebang
      - id: check-executables-have-shebangs
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Checks for symlinks which do not point to anything
      - id: check-symlinks
      # This hook checks yaml files for parseable syntax
      - id: check-yaml
        files: .drone.yml
        # Drone CI config allows and requires multiple documents
        args: [--allow-multiple-documents]
      - id: check-yaml
        exclude: .drone.yml
      # Detects the presence of private keys
      - id: detect-private-key
      # Ensures that a file is either empty, or ends with one newline
      - id: end-of-file-fixer
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
      # This hook trims trailing whitespace
      - id: trailing-whitespace
